### ISSUE TITLE
Bug: GitHub Logo disappears on dark theme

### ISSUE THREAD

**Issue by nzakas** [eslint/new.eslint.org#132]
### URL(s)

https://new.eslint.org/donate

### What did you do?

Went to the page on dark mode

### What did you expect to happen?

To see the GitHub logo next to the “GitHub Sponsors” text. 

### What actually happened?

The logo is missing because it’s dark-on-dark. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
@SaraSoueidan what do you think is the best way to address this?

**Comment by SaraSoueidan** [comment]
I'm thinking it's best we use a (circular) JPG instead of a PNG with transparency for the Github logo, so the image is white with the black logo inside. What do you think? And would you want to use the same treatment for the Open Collective logo for consistency?
