### ISSUE TITLE
Bug: wrong page title on blog category pages

### ISSUE THREAD

**Issue by bellangerq** [eslint/new.eslint.org#155]
### URL(s)

Every blog category page such as:
- https://new.eslint.org/blog/category/announcements/
- https://new.eslint.org/blog/category/api-changes/

And so on.

### What did you do?

- Navigate to a blog category page like [Announcements](https://new.eslint.org/blog/category/announcements/).
- Check the page title in the browser tab or in the devtools (`<head>` -> `<title>`).

### What did you expect to happen?

I expect the category name to be present in the page title. Something like:

`Announcements - ESLint - Pluggable JavaScript Linter`

### What actually happened?

The title has the value `undefined - ESLint - Pluggable JavaScript Linter`.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Confirmed. I'll take a look, thanks for the report.
