### ISSUE TITLE
Translate to Spanish 🪐

### ISSUE THREAD

**Issue by luifermoron** [eslint/new.eslint.org#158]
### What language do you want to translate the website into?

Spanish

### What is the language code for the language?

ES

### What is the locale code for the language?

es

### What help will you need?

Nothing by the moment. I will let you know if any roadblock arrive.

### Implementation Checklist

- [x] Create new site file
- [x] Set up Netlify project
- [x] Register new domain name
- [x] Set up Google Analytics
- [x] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Spanish is too wide. I will try to make as much as neutral as I can. I am planning to review another library docs first (like React  etc).

If any suggestion, just let me know.

**Comment by nzakas** [comment]
Awesome, thanks so much for offering to do this. You can go ahead and let us know if you need any help.

**Comment by luifermoron** [comment]
Any Idea why P tag is shown in that way?

![Screen Shot 2022-03-21 at 17 21 23](https://user-images.githubusercontent.com/26443806/159366947-db8ac814-3d75-4fb6-9b50-44f7308e6144.png)

In the other hand,
After deleting node_modules, css and _sites folders,running all commands again and finally changing to English it shows the same.
![Screen Shot 2022-03-21 at 17 28 44](https://user-images.githubusercontent.com/26443806/159367184-466046d9-5fc1-4a53-ba39-633fa10e8fea.png)

**Comment by nzakas** [comment]
There was a rendering bug that was fixed. If you rebase on top of main it should be fixed.

**Comment by nzakas** [comment]
This site has launched: https://es.eslint.org

Just waiting to hear back on whether Carbon Ads does ads in Spanish.

**Comment by luifermoron** [comment]
Extremely happy to see this! 

If original site changes something, just let me know. I can translate it in the future too.

**Comment by nzakas** [comment]
Thanks, we appreciate it!
