### ISSUE TITLE
Translate to French

### ISSUE THREAD

**Issue by darahak** [eslint/new.eslint.org#162]
### What language do you want to translate the website into?

French

### What is the language code for the language?

FR

### What is the locale code for the language?

fr

### What help will you need?

Can't think of anything right now, but maybe something will come up later.

### Implementation Checklist

- [x] Create new site file
- [x] Set up Netlify project
- [x] Register new domain name
- [ ] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks, we would love a French version. @Brack0 was also interested. Perhaps you could work together?

**Comment by darahak** [comment]
@Brack0 Wanna split it in half and review each other's parts? I already translated a few blocks from the top.

**Comment by Brack0** [comment]
Sure :)

**Comment by nzakas** [comment]
Hey folks, are you still working on this?

**Comment by darahak** [comment]
> Hey folks, are you still working on this?

Hey, I did something like 20%, but I've put this on hold for health reasons. I didn't check with @Brack0 though.

I might be able to pick this up next week.

**Comment by nzakas** [comment]
Thanks for the update. Take care of yourself!

**Comment by darahak** [comment]
@nzakas Just letting you know, I started to work on it again.

**Comment by nzakas** [comment]
Great, thanks! If you ever want to submit a partial pull request, we can also ask the community to help by adding suggestions to it.

**Comment by Brack0** [comment]
Hey, (some update)

I'm pushing FR translations to @darahak (https://github.com/darahak/new.eslint.org/pull/1).

@nzakas Is there any linter for yml files ? Or at least a max line length ? (No worries, I just want to provide a clean file)

**Comment by nzakas** [comment]
We don’t have a longer set up at this point. Generally we wrap files at around column 80, but you can do whatever makes it easiest for you to read.

**Comment by darahak** [comment]
@nzakas I finished translating the file. I'm gonna run a local version to make sure I didn't break anything and open a PR right after.

**Comment by nzakas** [comment]
The new site is now live!

https://fr.eslint.org/

I've submitted #221 to add Google Analytics.

I'll check on the ads.

**Comment by btmills** [comment]
#221 is merged, and I'm seeing ads on the live site, so closing as complete!
