### ISSUE TITLE
Translate to French

### ISSUE THREAD

**Issue by Brack0** [eslint/new.eslint.org#163]
### What language do you want to translate the website into?

French

### What is the language code for the language?

FR

### What is the locale code for the language?

fr

### What help will you need?

Nothing for now.

### Implementation Checklist

- [ ] Create new site file
- [ ] Set up Netlify project
- [ ] Register new domain name
- [ ] Set up Google Analytics
- [ ] Set up Carbon Ads

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Should I update technical parts (google analytics, ads, etc) ?
Is there any deadline for this ?

**Comment by nzakas** [comment]
Duplicate of #162. Let’s see if you can work together?
