### ISSUE TITLE
Bug: improve selection color for install command

### ISSUE THREAD

**Issue by snitin315** [eslint/new.eslint.org#190]
### URL(s)

https://new.eslint.org/

### What did you do?

Select the install command. The selection color is white which is not at all visible in the light theme. Also in the dark theme text color doesn't change on selection making it hard to read the actual command after selection.

<img width="450" alt="Screenshot 2022-04-16 at 7 06 54 AM" src="https://user-images.githubusercontent.com/46647141/163656822-6cda52c7-6da5-4370-a355-3d51fc80e664.png">

<img width="417" alt="Screenshot 2022-04-16 at 7 07 17 AM" src="https://user-images.githubusercontent.com/46647141/163656823-3c899c97-99c7-4c45-a0ff-f62fd3088be8.png">

### What did you expect to happen?

The selection color should be purple, just like at the rest of the places.

<img width="796" alt="Screenshot 2022-04-16 at 7 10 17 AM" src="https://user-images.githubusercontent.com/46647141/163656902-cc4dbd2d-b586-4bab-bfa9-f0b5323b74ca.png">

<img width="822" alt="Screenshot 2022-04-16 at 7 10 43 AM" src="https://user-images.githubusercontent.com/46647141/163656936-d3ccd952-db49-457f-9bcd-9caaeab0f249.png">

### What actually happened?

The selection color was white.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Sounds good to me. 👍

**Comment by snitin315** [comment]
Fixed in https://github.com/eslint/new.eslint.org/pull/194
