### ISSUE TITLE
Bug: theme switcher was not displayed well with cn

### ISSUE THREAD

**Issue by aladdin-add** [eslint/new.eslint.org#197]
### URL(s)

it was not deployed yet. I was using my dev: http://localhost:2022/

### What did you do?

just scroll to the bottom.

### What did you expect to happen?

"深色"/ "浅色" should be display in one line.

### What actually happened?

![image](https://user-images.githubusercontent.com/13050025/164666313-58f851d2-ff2a-4cc0-aee9-03ac759843ab.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I've added a `white-space: nowrap;` in my local, it seems fixed the issue. I can make a PR if it's the right way to go. /cc @SaraSoueidan

**Comment by harish-sethuraman** [comment]
I've sent a fix for this 😅

**Comment by ota-meshi** [comment]
FYI, `ja` #193 have the same problem.

<img width="263" alt="image" src="https://user-images.githubusercontent.com/16508807/164727168-ea6b9181-2618-4d49-9f64-aea8cde2a8ba.png">
