### ISSUE TITLE
Sitemaps

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/new.eslint.org#232]
We will have an additional sitemap at `https://eslint.org/docs/latest/sitemap.xml`, but will search engine crawlers be aware of it? Should we add a sitemap index file?

Also, we are using domain-relative URLs in `<loc>`, for example `<loc>/blog/2014/01/breaking-change-formatter/</loc>`. Per https://www.sitemaps.org/protocol.html#locdef this URL must begin with the protocol.

**Comment by nzakas** [comment]
I’m not very familiar with site map best practices, but an index sounds reasonable. Is that something you can take on?

**Comment by harish-sethuraman** [comment]
> We will have an additional sitemap at https://eslint.org/docs/latest/sitemap.xml, but will search engine crawlers be aware of it? Should we add a sitemap index file?

We have to include them in the robots.txt like the following for crawlers to be aware of it

```
User-agent: *
Allow: /

Sitemap: https://eslint.org/docs/latest/sitemap.xml
```
