### ISSUE TITLE
Rebuild and publish playground after releases

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/new.eslint.org#233]
Ideally, after each ESLint release the playground would be automatically re-built with the new version of ESLint and published.

This looks like a good case for the use of Netlify build hooks, assuming that the build hooks trigger all of build -> deploy -> publish.

**Comment by nzakas** [comment]
Build hooks only rebuild what’s in the repo already. We would also need a way to update the ESLint version in package.json. I was going to check and see if there was a way to trigger a GitHub workflow based on a release in another repo. Worst case, we could build this into the bot.

**Comment by mdjermanovic** [comment]
Version in the root is used to lint the playground repo.

The version we're building the playground from is in `src/playground/node_modules/eslint`. It's always [installed](https://github.com/eslint/playground/blob/3b54c11b88ba1afe583f8fd0283816ac6a9a94b3/package.json#L14) by the build script as ["eslint": "latest"](https://github.com/eslint/playground/blob/3b54c11b88ba1afe583f8fd0283816ac6a9a94b3/src/playground/package.json#L8-L9). A full rebuild should do the work without the need to update anything in the repo. A problem could be only Netlify's change detection if it applies when the build is triggered by a hook.

**Comment by mdjermanovic** [comment]
I've just tried with a build hook and it has successfully published playground with ESLint v8.18.0

**Comment by nzakas** [comment]
Oh nice! :tada: So I guess all we need is a workflow to trigger the build hook on release?

**Comment by mdjermanovic** [comment]
> all we need is a workflow to trigger the build hook on release?

Yes, that should work well in this case

**Comment by mdjermanovic** [comment]
https://github.com/eslint/eslint/pull/16034
